#!/usr/bin/env python3
"""
generate_index.py — Generate site-wide machine-readable indexes for rqm-tech-papers.

Reads all paper folders under papers/ and generates:
  index/papers.json    — All paper metadata in one file
  index/claims.json    — All claims across all papers
  index/notation.json  — All notation entries across all papers
  index/glossary.json  — All glossary terms across all papers

Usage:
    python3 scripts/generate_index.py [--output-dir OUTPUT_DIR]

Exit codes:
    0 — indexes generated successfully
    1 — error during generation
"""

import argparse
import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

# ── Configuration ─────────────────────────────────────────────────────────────

REPO_ROOT = Path(__file__).resolve().parent.parent
PAPERS_DIR = REPO_ROOT / "papers"
INDEX_DIR = REPO_ROOT / "index"

# ── Helpers ───────────────────────────────────────────────────────────────────


def load_json(path: Path) -> dict | list | None:
    """Load and parse a JSON file, returning None on error."""
    try:
        with open(path, encoding="utf-8") as f:
            return json.load(f)
    except (json.JSONDecodeError, OSError) as e:
        print(f"  Warning: could not read {path}: {e}", file=sys.stderr)
        return None


def write_json(path: Path, data: object) -> None:
    """Write data as pretty-printed JSON to path."""
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
        f.write("\n")
    print(f"  Written: {path.relative_to(REPO_ROOT)}")


def get_paper_dirs(papers_dir: Path) -> list[Path]:
    """Return sorted list of paper directories."""
    if not papers_dir.exists():
        return []
    return sorted(
        [d for d in papers_dir.iterdir() if d.is_dir()],
        key=lambda d: d.name,
    )


# ── Index generators ──────────────────────────────────────────────────────────


def generate_papers_index(paper_dirs: list[Path]) -> dict:
    """Generate the site-wide papers.json index."""
    papers = []

    for paper_dir in paper_dirs:
        metadata_path = paper_dir / "metadata.json"
        metadata = load_json(metadata_path)
        if metadata is None:
            print(f"  Warning: skipping {paper_dir.name} — metadata.json missing or invalid")
            continue

        # Add relative paths for convenience
        entry = dict(metadata)
        entry["_path"] = f"papers/{paper_dir.name}/"
        entry["_html"] = f"papers/{paper_dir.name}/paper.html"
        entry["_pdf"] = f"papers/{paper_dir.name}/paper.pdf"
        entry["_metadata"] = f"papers/{paper_dir.name}/metadata.json"
        entry["_claims"] = f"papers/{paper_dir.name}/claims.json"
        entry["_notation"] = f"papers/{paper_dir.name}/notation.json"
        entry["_glossary"] = f"papers/{paper_dir.name}/glossary.json"
        entry["_jats"] = f"papers/{paper_dir.name}/paper.jats.xml"
        papers.append(entry)

    return {
        "_generated": datetime.now(timezone.utc).isoformat(),
        "_description": "Site-wide index of all papers in the RQM Technologies technical paper series.",
        "_source": "Generated by scripts/generate_index.py",
        "total": len(papers),
        "papers": papers,
    }


def generate_claims_index(paper_dirs: list[Path]) -> dict:
    """Generate the site-wide claims.json index."""
    all_claims = []

    for paper_dir in paper_dirs:
        claims_path = paper_dir / "claims.json"
        data = load_json(claims_path)
        if data is None or not isinstance(data, dict):
            continue

        paper_id = data.get("paper_id", paper_dir.name)
        claims = data.get("claims", [])

        for claim in claims:
            entry = dict(claim)
            entry["_paper_id"] = paper_id
            entry["_paper_path"] = f"papers/{paper_dir.name}/"
            # Qualify claim_id with paper_id to ensure global uniqueness
            entry["_global_claim_id"] = f"{paper_id}:{claim.get('claim_id', '')}"
            all_claims.append(entry)

    return {
        "_generated": datetime.now(timezone.utc).isoformat(),
        "_description": "Site-wide index of all claims across all papers in the series.",
        "_source": "Generated by scripts/generate_index.py",
        "total": len(all_claims),
        "claims": all_claims,
    }


def generate_notation_index(paper_dirs: list[Path]) -> dict:
    """Generate the site-wide notation.json index."""
    all_notation = []

    for paper_dir in paper_dirs:
        notation_path = paper_dir / "notation.json"
        data = load_json(notation_path)
        if data is None or not isinstance(data, dict):
            continue

        paper_id = data.get("paper_id", paper_dir.name)
        notation = data.get("notation", [])

        for entry in notation:
            item = dict(entry)
            item["_paper_id"] = paper_id
            item["_paper_path"] = f"papers/{paper_dir.name}/"
            all_notation.append(item)

    return {
        "_generated": datetime.now(timezone.utc).isoformat(),
        "_description": "Site-wide index of all notation and symbols across all papers in the series.",
        "_source": "Generated by scripts/generate_index.py",
        "total": len(all_notation),
        "notation": all_notation,
    }


def generate_glossary_index(paper_dirs: list[Path]) -> dict:
    """Generate the site-wide glossary.json index."""
    all_terms = []
    seen_terms: dict[str, list[str]] = {}  # term → [paper_ids]

    for paper_dir in paper_dirs:
        glossary_path = paper_dir / "glossary.json"
        data = load_json(glossary_path)
        if data is None or not isinstance(data, dict):
            continue

        paper_id = data.get("paper_id", paper_dir.name)
        glossary = data.get("glossary", [])

        for entry in glossary:
            term = entry.get("term", "")
            item = dict(entry)
            item["_paper_id"] = paper_id
            item["_paper_path"] = f"papers/{paper_dir.name}/"
            all_terms.append(item)

            if term:
                seen_terms.setdefault(term, []).append(paper_id)

    # Identify terms defined in multiple papers
    cross_paper_terms = {t: papers for t, papers in seen_terms.items() if len(papers) > 1}

    return {
        "_generated": datetime.now(timezone.utc).isoformat(),
        "_description": "Site-wide index of all glossary terms across all papers in the series.",
        "_source": "Generated by scripts/generate_index.py",
        "total": len(all_terms),
        "cross_paper_terms": cross_paper_terms,
        "glossary": all_terms,
    }


# ── Main ──────────────────────────────────────────────────────────────────────


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate site-wide machine-readable indexes for rqm-tech-papers."
    )
    parser.add_argument(
        "--output-dir",
        default=str(INDEX_DIR),
        help=f"Directory to write index files (default: {INDEX_DIR})",
    )
    args = parser.parse_args()

    output_dir = Path(args.output_dir)

    if not PAPERS_DIR.exists():
        print(f"Error: papers directory not found at {PAPERS_DIR}")
        return 1

    paper_dirs = get_paper_dirs(PAPERS_DIR)

    if not paper_dirs:
        print("No paper directories found. Index files will be empty.")

    print(f"Found {len(paper_dirs)} paper(s): {[d.name for d in paper_dirs]}")
    print(f"Writing indexes to: {output_dir}\n")

    write_json(output_dir / "papers.json", generate_papers_index(paper_dirs))
    write_json(output_dir / "claims.json", generate_claims_index(paper_dirs))
    write_json(output_dir / "notation.json", generate_notation_index(paper_dirs))
    write_json(output_dir / "glossary.json", generate_glossary_index(paper_dirs))

    print("\nIndex generation complete.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
